// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethodOpenClose - Use 'RecordedMethodOpenCloseParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodOpenClose()
        {
            #region Variable Declarations
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIЗакрытьButton;
            WinButton uIЗакрытьButton1 = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.RecordedMethodOpenCloseParams.UIТерминалV10WindowExePath, this.RecordedMethodOpenCloseParams.UIТерминалV10WindowAlternateExePath);

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(40, 12));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(40, 12));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton1, new Point(40, 15));
        }
        
        /// <summary>
        /// SendCommand - Use 'SendCommandParams' to pass parameters into this method.
        /// </summary>
        public void SendCommand()
        {
            #region Variable Declarations
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            WinEdit uITb_send_commandEdit = this.UIТерминалV10Window.UITb_send_commandWindow.UITb_send_commandEdit;
            WinButton uIОтправитьButton = this.UIТерминалV10Window.UIОтправитьWindow.UIОтправитьButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.SendCommandParams.UIТерминалV10WindowExePath, this.SendCommandParams.UIТерминалV10WindowAlternateExePath);

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(16, 16));

            // Type '@LED_ON' in 'tb_send_command' text box
            uITb_send_commandEdit.Text = this.SendCommandParams.UITb_send_commandEditText;

            // Click 'Отправить' button
            Mouse.Click(uIОтправитьButton, new Point(52, 10));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(33, 9));
        }
        
        /// <summary>
        /// SendCommandNotOpen - Use 'SendCommandNotOpenParams' to pass parameters into this method.
        /// </summary>
        public void SendCommandNotOpen()
        {
            #region Variable Declarations
            WinEdit uITb_send_commandEdit = this.UIТерминалV10Window.UITb_send_commandWindow.UITb_send_commandEdit;
            WinButton uIОтправитьButton = this.UIТерминалV10Window.UIОтправитьWindow.UIОтправитьButton;
            WinButton uIОКButton = this.UIErrorWindow.UIОКWindow.UIОКButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.SendCommandNotOpenParams.UIТерминалV10WindowExePath, this.SendCommandNotOpenParams.UIТерминалV10WindowAlternateExePath);

            // Type '@LED_ON' in 'tb_send_command' text box
            uITb_send_commandEdit.Text = this.SendCommandNotOpenParams.UITb_send_commandEditText;

            // Click 'Отправить' button
            Mouse.Click(uIОтправитьButton, new Point(46, 18));

            // Click 'ОК' button
            Mouse.Click(uIОКButton, new Point(38, 14));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(31, 16));
        }
        
        /// <summary>
        /// SendFileBin - Use 'SendFileBinParams' to pass parameters into this method.
        /// </summary>
        public void SendFileBin()
        {
            #region Variable Declarations
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            WinButton uIОткрытьфайлButton = this.UIТерминалV10Window.UIОткрытьфайлWindow.UIОткрытьфайлButton;
            WinEdit uIИмяEdit = this.UIОткрытьWindow.UIItemWindow.UITest_bintxtListItem.UIИмяEdit;
            WinButton uIОтправитьфайлButton = this.UIТерминалV10Window.UIОтправитьфайлWindow.UIОтправитьфайлButton;
            WinButton uIОКButton = this.UIErrorWindow.UIОКWindow.UIОКButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIЗакрытьButton;
            WinButton uIЗакрытьButton1 = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(16, 4));

            // Click 'Открыть файл...' button
            Mouse.Click(uIОткрытьфайлButton, new Point(53, 12));

            // Double-Click 'Имя' text box
            Mouse.DoubleClick(uIИмяEdit, new Point(26, 11));

            // Click 'Отправить файл' button
            Mouse.Click(uIОтправитьфайлButton, new Point(77, 12));

            // Type '{Enter}' in 'ОК' button
            Keyboard.SendKeys(uIОКButton, this.SendFileBinParams.UIОКButtonSendKeys, ModifierKeys.None);

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(33, 11));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton1, new Point(30, 10));
        }
        
        /// <summary>
        /// SendFileEmty - Use 'SendFileEmtyParams' to pass parameters into this method.
        /// </summary>
        public void SendFileEmty()
        {
            #region Variable Declarations
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            WinButton uIОткрытьфайлButton = this.UIТерминалV10Window.UIОткрытьфайлWindow.UIОткрытьфайлButton;
            WinEdit uIИмяEdit = this.UIОткрытьWindow.UIItemWindow.UITest_emptytxtListItem.UIИмяEdit;
            WinSplitButton uIОткрытьSplitButton = this.UIОткрытьWindow.UIОткрытьWindow1.UIОткрытьSplitButton;
            WinButton uIОтправитьфайлButton = this.UIТерминалV10Window.UIОтправитьфайлWindow.UIОтправитьфайлButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIЗакрытьButton;
            WinButton uIЗакрытьButton1 = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.SendFileEmtyParams.UIТерминалV10WindowExePath, this.SendFileEmtyParams.UIТерминалV10WindowAlternateExePath);

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(14, 13));

            // Click 'Открыть файл...' button
            Mouse.Click(uIОткрытьфайлButton, new Point(69, 7));

            // Click 'Имя' text box
            Mouse.Click(uIИмяEdit, new Point(82, 11));

            // Click '&Открыть' split button
            Mouse.Click(uIОткрытьSplitButton, new Point(15, 10));

            // Click 'Отправить файл' button
            Mouse.Click(uIОтправитьфайлButton, new Point(88, 10));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(23, 11));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton1, new Point(33, 5));
        }
        
        /// <summary>
        /// SendFileNotOpen - Use 'SendFileNotOpenParams' to pass parameters into this method.
        /// </summary>
        public void SendFileNotOpen()
        {
            #region Variable Declarations
            WinButton uIОтправитьфайлButton = this.UIТерминалV10Window.UIОтправитьфайлWindow.UIОтправитьфайлButton;
            WinButton uIОКButton = this.UIErrorWindow.UIОКWindow.UIОКButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.SendFileNotOpenParams.UIТерминалV10WindowExePath, this.SendFileNotOpenParams.UIТерминалV10WindowAlternateExePath);

            // Click 'Отправить файл' button
            Mouse.Click(uIОтправитьфайлButton, new Point(97, 11));

            // Click 'ОК' button
            Mouse.Click(uIОКButton, new Point(53, 13));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(36, 15));
        }
        
        /// <summary>
        /// SendFileOk - Use 'SendFileOkParams' to pass parameters into this method.
        /// </summary>
        public void SendFileOk()
        {
            #region Variable Declarations
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            WinButton uIОткрытьфайлButton = this.UIТерминалV10Window.UIОткрытьфайлWindow.UIОткрытьфайлButton;
            WinEdit uIИмяEdit = this.UIОткрытьWindow.UIItemWindow.UITest_oktxtListItem.UIИмяEdit;
            WinSplitButton uIОткрытьSplitButton = this.UIОткрытьWindow.UIОткрытьWindow1.UIОткрытьSplitButton;
            WinButton uIОтправитьфайлButton = this.UIТерминалV10Window.UIОтправитьфайлWindow.UIОтправитьфайлButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.SendFileOkParams.UIТерминалV10WindowExePath, this.SendFileOkParams.UIТерминалV10WindowAlternateExePath);

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(13, 10));

            // Click 'Открыть файл...' button
            Mouse.Click(uIОткрытьфайлButton, new Point(31, 12));

            // Click 'Имя' text box
            Mouse.Click(uIИмяEdit, new Point(51, 8));

            // Click '&Открыть' split button
            Mouse.Click(uIОткрытьSplitButton, new Point(15, 14));

            // Click 'Отправить файл' button
            Mouse.Click(uIОтправитьфайлButton, new Point(49, 6));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(27, 3));
        }
        
        /// <summary>
        /// Recieve - Use 'RecieveParams' to pass parameters into this method.
        /// </summary>
        public void Recieve()
        {
            #region Variable Declarations
            //WinButton uIConnectButton = this.UIТерминалV10Window.UIItemWindow.UIТерминалV10Client.UIConnectButton;
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            //WinEdit uIItemEdit = this.UIТерминалV10Window.UIItemWindow1.UIItemEdit;
            //WinButton uISendButton = this.UIТерминалV10Window.UIItemWindow2.UIТерминалV10Client.UISendButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            WinButton uIЗакрытьButton1 = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.RecieveParams.UIТерминалV10WindowExePath, this.RecieveParams.UIТерминалV10WindowAlternateExePath);

            // Click 'Connect' button
            //Mouse.Click(uIConnectButton, new Point(58, 9));

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(10, 13));

            // Click text box
            //Mouse.Click(uIItemEdit, new Point(140, 11));

            // Click '-> Send' button
            //Mouse.Click(uISendButton, new Point(45, 11));

            // Type '{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}' in '-> Send' button
            //Keyboard.SendKeys(uISendButton, this.RecieveParams.UISendButtonSendKeys, ModifierKeys.None);

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(34, 11));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton1, new Point(35, 4));
        }
        
        /// <summary>
        /// Recieve2 - Use 'Recieve2Params' to pass parameters into this method.
        /// </summary>
        public void Recieve2()
        {
            #region Variable Declarations
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            WinComboBox uICb_portComboBox = this.UIТерминалV10Window1.UICb_portWindow.UICb_portComboBox;
            WinButton uIОткрытьButton1 = this.UIТерминалV10Window1.UIОткрытьWindow.UIОткрытьButton;
            WinEdit uITb_send_commandEdit = this.UIТерминалV10Window1.UITb_send_commandWindow.UITb_send_commandEdit;
            WinButton uIОтправитьButton = this.UIТерминалV10Window1.UIОтправитьWindow.UIОтправитьButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window1.UIОткрытьWindow.UIЗакрытьButton;
            WinButton uIЗакрытьButton1 = this.UIТерминалV10Window1.UIТерминалV10TitleBar.UIЗакрытьButton;
            WinButton uIЗакрытьButton2 = this.UIТерминалV10Window.UIОткрытьWindow.UIЗакрытьButton;
            WinButton uIЗакрытьButton3 = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.Recieve2Params.UIТерминалV10WindowExePath, this.Recieve2Params.UIТерминалV10WindowAlternateExePath);

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(33, 12));

            // Select 'COM29' in 'cb_port' combo box
            uICb_portComboBox.SelectedItem = this.Recieve2Params.UICb_portComboBoxSelectedItem;

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton1, new Point(52, 9));

            // Type 'test' in 'tb_send_command' text box
            uITb_send_commandEdit.Text = this.Recieve2Params.UITb_send_commandEditText;

            // Click 'Отправить' button
            Mouse.Click(uIОтправитьButton, new Point(31, 6));

            // Type '{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}' in 'Отправить' button
            Keyboard.SendKeys(uIОтправитьButton, this.Recieve2Params.UIОтправитьButtonSendKeys, ModifierKeys.None);

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(34, 9));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton1, new Point(21, 12));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton2, new Point(44, 1));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton3, new Point(30, 11));
        }
        
        #region Properties
        public virtual RecordedMethodOpenCloseParams RecordedMethodOpenCloseParams
        {
            get
            {
                if ((this.mRecordedMethodOpenCloseParams == null))
                {
                    this.mRecordedMethodOpenCloseParams = new RecordedMethodOpenCloseParams();
                }
                return this.mRecordedMethodOpenCloseParams;
            }
        }
        
        public virtual SendCommandParams SendCommandParams
        {
            get
            {
                if ((this.mSendCommandParams == null))
                {
                    this.mSendCommandParams = new SendCommandParams();
                }
                return this.mSendCommandParams;
            }
        }
        
        public virtual SendCommandNotOpenParams SendCommandNotOpenParams
        {
            get
            {
                if ((this.mSendCommandNotOpenParams == null))
                {
                    this.mSendCommandNotOpenParams = new SendCommandNotOpenParams();
                }
                return this.mSendCommandNotOpenParams;
            }
        }
        
        public virtual SendFileBinParams SendFileBinParams
        {
            get
            {
                if ((this.mSendFileBinParams == null))
                {
                    this.mSendFileBinParams = new SendFileBinParams();
                }
                return this.mSendFileBinParams;
            }
        }
        
        public virtual SendFileEmtyParams SendFileEmtyParams
        {
            get
            {
                if ((this.mSendFileEmtyParams == null))
                {
                    this.mSendFileEmtyParams = new SendFileEmtyParams();
                }
                return this.mSendFileEmtyParams;
            }
        }
        
        public virtual SendFileNotOpenParams SendFileNotOpenParams
        {
            get
            {
                if ((this.mSendFileNotOpenParams == null))
                {
                    this.mSendFileNotOpenParams = new SendFileNotOpenParams();
                }
                return this.mSendFileNotOpenParams;
            }
        }
        
        public virtual SendFileOkParams SendFileOkParams
        {
            get
            {
                if ((this.mSendFileOkParams == null))
                {
                    this.mSendFileOkParams = new SendFileOkParams();
                }
                return this.mSendFileOkParams;
            }
        }
        
        public virtual RecieveParams RecieveParams
        {
            get
            {
                if ((this.mRecieveParams == null))
                {
                    this.mRecieveParams = new RecieveParams();
                }
                return this.mRecieveParams;
            }
        }
        
        public virtual Recieve2Params Recieve2Params
        {
            get
            {
                if ((this.mRecieve2Params == null))
                {
                    this.mRecieve2Params = new Recieve2Params();
                }
                return this.mRecieve2Params;
            }
        }
        
        public UIТерминалV10Window UIТерминалV10Window
        {
            get
            {
                if ((this.mUIТерминалV10Window == null))
                {
                    this.mUIТерминалV10Window = new UIТерминалV10Window();
                }
                return this.mUIТерминалV10Window;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIErrorWindow UIErrorWindow
        {
            get
            {
                if ((this.mUIErrorWindow == null))
                {
                    this.mUIErrorWindow = new UIErrorWindow();
                }
                return this.mUIErrorWindow;
            }
        }
        
        public UIОткрытьWindow2 UIОткрытьWindow
        {
            get
            {
                if ((this.mUIОткрытьWindow == null))
                {
                    this.mUIОткрытьWindow = new UIОткрытьWindow2();
                }
                return this.mUIОткрытьWindow;
            }
        }
        
        public UITerminal1_9_bWindow UITerminal1_9_bWindow
        {
            get
            {
                if ((this.mUITerminal1_9_bWindow == null))
                {
                    this.mUITerminal1_9_bWindow = new UITerminal1_9_bWindow();
                }
                return this.mUITerminal1_9_bWindow;
            }
        }
        
        public UIТерминалV10Window UIТерминалV102Window
        {
            get
            {
                if ((this.mUIТерминалV10Window == null))
                {
                    this.mUIТерминалV10Window = new UIТерминалV10Window();
                }
                return this.mUIТерминалV10Window;
            }
        }
        
        public UIТерминалV10Window1 UIТерминалV10Window1
        {
            get
            {
                if ((this.mUIТерминалV10Window1 == null))
                {
                    this.mUIТерминалV10Window1 = new UIТерминалV10Window1();
                }
                return this.mUIТерминалV10Window1;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethodOpenCloseParams mRecordedMethodOpenCloseParams;
        
        private SendCommandParams mSendCommandParams;
        
        private SendCommandNotOpenParams mSendCommandNotOpenParams;
        
        private SendFileBinParams mSendFileBinParams;
        
        private SendFileEmtyParams mSendFileEmtyParams;
        
        private SendFileNotOpenParams mSendFileNotOpenParams;
        
        private SendFileOkParams mSendFileOkParams;
        
        private RecieveParams mRecieveParams;
        
        private Recieve2Params mRecieve2Params;
        
        private UIТерминалV10Window mUIТерминалV10Window;
        
        private UIDebugWindow mUIDebugWindow;
        
        private UIErrorWindow mUIErrorWindow;
        
        private UIОткрытьWindow2 mUIОткрытьWindow;
        
        private UITerminal1_9_bWindow mUITerminal1_9_bWindow;
        
        private UIТерминалV10Window mUIТерминалV102Window;
        
        private UIТерминалV10Window1 mUIТерминалV10Window1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodOpenClose'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethodOpenCloseParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SendCommand'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SendCommandParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Type '@LED_ON' in 'tb_send_command' text box
        /// </summary>
        public string UITb_send_commandEditText = "@LED_ON";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SendCommandNotOpen'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SendCommandNotOpenParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Type '@LED_ON' in 'tb_send_command' text box
        /// </summary>
        public string UITb_send_commandEditText = "@LED_ON";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SendFileBin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SendFileBinParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{Enter}' in 'ОК' button
        /// </summary>
        public string UIОКButtonSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SendFileEmty'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SendFileEmtyParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SendFileNotOpen'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SendFileNotOpenParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SendFileOk'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class SendFileOkParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Recieve'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecieveParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Type '{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}' in '-> Send' button
        /// </summary>
        public string UISendButtonSendKeys = "{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Ent" +
            "er}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Recieve2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class Recieve2Params
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\Terminal\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\Terminal\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Select 'COM29' in 'cb_port' combo box
        /// </summary>
        public string UICb_portComboBoxSelectedItem = "COM29";
        
        /// <summary>
        /// Type 'test' in 'tb_send_command' text box
        /// </summary>
        public string UITb_send_commandEditText = "test";
        
        /// <summary>
        /// Type '{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}' in 'Отправить' button
        /// </summary>
        public string UIОтправитьButtonSendKeys = "{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Ent" +
            "er}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10Window : WinWindow
    {
        
        public UIТерминалV10Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Терминал V1.0";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public UIОткрытьWindow UIОткрытьWindow
        {
            get
            {
                if ((this.mUIОткрытьWindow == null))
                {
                    this.mUIОткрытьWindow = new UIОткрытьWindow(this);
                }
                return this.mUIОткрытьWindow;
            }
        }
        
        public UIТерминалV10TitleBar UIТерминалV10TitleBar
        {
            get
            {
                if ((this.mUIТерминалV10TitleBar == null))
                {
                    this.mUIТерминалV10TitleBar = new UIТерминалV10TitleBar(this);
                }
                return this.mUIТерминалV10TitleBar;
            }
        }
        
        public UITb_send_commandWindow UITb_send_commandWindow
        {
            get
            {
                if ((this.mUITb_send_commandWindow == null))
                {
                    this.mUITb_send_commandWindow = new UITb_send_commandWindow(this);
                }
                return this.mUITb_send_commandWindow;
            }
        }
        
        public UIОтправитьWindow UIОтправитьWindow
        {
            get
            {
                if ((this.mUIОтправитьWindow == null))
                {
                    this.mUIОтправитьWindow = new UIОтправитьWindow(this);
                }
                return this.mUIОтправитьWindow;
            }
        }
        
        public UIОтправитьфайлWindow UIОтправитьфайлWindow
        {
            get
            {
                if ((this.mUIОтправитьфайлWindow == null))
                {
                    this.mUIОтправитьфайлWindow = new UIОтправитьфайлWindow(this);
                }
                return this.mUIОтправитьфайлWindow;
            }
        }
        
        public UIТерминалV10Client UIТерминалV10Client
        {
            get
            {
                if ((this.mUIТерминалV10Client == null))
                {
                    this.mUIТерминалV10Client = new UIТерминалV10Client(this);
                }
                return this.mUIТерминалV10Client;
            }
        }
        
        public UIОткрытьфайлWindow UIОткрытьфайлWindow
        {
            get
            {
                if ((this.mUIОткрытьфайлWindow == null))
                {
                    this.mUIОткрытьфайлWindow = new UIОткрытьфайлWindow(this);
                }
                return this.mUIОткрытьфайлWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIОткрытьWindow mUIОткрытьWindow;
        
        private UIТерминалV10TitleBar mUIТерминалV10TitleBar;
        
        private UITb_send_commandWindow mUITb_send_commandWindow;
        
        private UIОтправитьWindow mUIОтправитьWindow;
        
        private UIОтправитьфайлWindow mUIОтправитьфайлWindow;
        
        private UIТерминалV10Client mUIТерминалV10Client;
        
        private UIОткрытьфайлWindow mUIОткрытьфайлWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОткрытьWindow : WinWindow
    {
        
        public UIОткрытьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_open_close";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIОткрытьButton
        {
            get
            {
                if ((this.mUIОткрытьButton == null))
                {
                    this.mUIОткрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОткрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Открыть";
                    this.mUIОткрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIОткрытьButton;
            }
        }
        
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОткрытьButton;
        
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10TitleBar : WinTitleBar
    {
        
        public UIТерминалV10TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITb_send_commandWindow : WinWindow
    {
        
        public UITb_send_commandWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tb_send_command";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinEdit UITb_send_commandEdit
        {
            get
            {
                if ((this.mUITb_send_commandEdit == null))
                {
                    this.mUITb_send_commandEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITb_send_commandEdit.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUITb_send_commandEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITb_send_commandEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОтправитьWindow : WinWindow
    {
        
        public UIОтправитьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_send";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIОтправитьButton
        {
            get
            {
                if ((this.mUIОтправитьButton == null))
                {
                    this.mUIОтправитьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОтправитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Отправить";
                    this.mUIОтправитьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIОтправитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОтправитьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОтправитьфайлWindow : WinWindow
    {
        
        public UIОтправитьфайлWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_send_file";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIОтправитьфайлButton
        {
            get
            {
                if ((this.mUIОтправитьфайлButton == null))
                {
                    this.mUIОтправитьфайлButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОтправитьфайлButton.SearchProperties[WinButton.PropertyNames.Name] = "Отправить файл";
                    this.mUIОтправитьфайлButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIОтправитьфайлButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОтправитьфайлButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10Client : WinClient
    {
        
        public UIТерминалV10Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Терминал V1.0";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinWindow UITb_send_commandWindow
        {
            get
            {
                if ((this.mUITb_send_commandWindow == null))
                {
                    this.mUITb_send_commandWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITb_send_commandWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITb_send_commandWindow.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUITb_send_commandWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITb_send_commandWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОткрытьфайлWindow : WinWindow
    {
        
        public UIОткрытьфайлWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_open_file";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIОткрытьфайлButton
        {
            get
            {
                if ((this.mUIОткрытьфайлButton == null))
                {
                    this.mUIОткрытьфайлButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОткрытьфайлButton.SearchProperties[WinButton.PropertyNames.Name] = "Открыть файл...";
                    this.mUIОткрытьфайлButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIОткрытьфайлButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОткрытьфайлButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Просмотр элементов";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UITerminalexeListItem UITerminalexeListItem
        {
            get
            {
                if ((this.mUITerminalexeListItem == null))
                {
                    this.mUITerminalexeListItem = new UITerminalexeListItem(this);
                }
                return this.mUITerminalexeListItem;
            }
        }
        #endregion
        
        #region Fields
        private UITerminalexeListItem mUITerminalexeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITerminalexeListItem : WinListItem
    {
        
        public UITerminalexeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Terminal.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UIИмяEdit
        {
            get
            {
                if ((this.mUIИмяEdit == null))
                {
                    this.mUIИмяEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIИмяEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Имя";
                    this.mUIИмяEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUIИмяEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIИмяEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIErrorWindow : WinWindow
    {
        
        public UIErrorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Error!";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Error!");
            #endregion
        }
        
        #region Properties
        public UIОКWindow UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow(this);
                }
                return this.mUIОКWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIОКWindow mUIОКWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОКWindow : WinWindow
    {
        
        public UIОКWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Error!");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("Error!");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОткрытьWindow2 : WinWindow
    {
        
        public UIОткрытьWindow2()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Открыть";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Открыть");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIОткрытьWindow1 UIОткрытьWindow1
        {
            get
            {
                if ((this.mUIОткрытьWindow1 == null))
                {
                    this.mUIОткрытьWindow1 = new UIОткрытьWindow1(this);
                }
                return this.mUIОткрытьWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        
        private UIОткрытьWindow1 mUIОткрытьWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Просмотр элементов";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Открыть");
            #endregion
        }
        
        #region Properties
        public UITest_emptytxtListItem UITest_emptytxtListItem
        {
            get
            {
                if ((this.mUITest_emptytxtListItem == null))
                {
                    this.mUITest_emptytxtListItem = new UITest_emptytxtListItem(this);
                }
                return this.mUITest_emptytxtListItem;
            }
        }
        
        public UITest_bintxtListItem UITest_bintxtListItem
        {
            get
            {
                if ((this.mUITest_bintxtListItem == null))
                {
                    this.mUITest_bintxtListItem = new UITest_bintxtListItem(this);
                }
                return this.mUITest_bintxtListItem;
            }
        }
        
        public UITest_oktxtListItem UITest_oktxtListItem
        {
            get
            {
                if ((this.mUITest_oktxtListItem == null))
                {
                    this.mUITest_oktxtListItem = new UITest_oktxtListItem(this);
                }
                return this.mUITest_oktxtListItem;
            }
        }
        #endregion
        
        #region Fields
        private UITest_emptytxtListItem mUITest_emptytxtListItem;
        
        private UITest_bintxtListItem mUITest_bintxtListItem;
        
        private UITest_oktxtListItem mUITest_oktxtListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITest_emptytxtListItem : WinListItem
    {
        
        public UITest_emptytxtListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "test_empty.txt";
            this.WindowTitles.Add("Открыть");
            #endregion
        }
        
        #region Properties
        public WinEdit UIИмяEdit
        {
            get
            {
                if ((this.mUIИмяEdit == null))
                {
                    this.mUIИмяEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIИмяEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Имя";
                    this.mUIИмяEdit.WindowTitles.Add("Открыть");
                    #endregion
                }
                return this.mUIИмяEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIИмяEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITest_bintxtListItem : WinListItem
    {
        
        public UITest_bintxtListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "test_bin.txt";
            this.WindowTitles.Add("Открыть");
            #endregion
        }
        
        #region Properties
        public WinEdit UIИмяEdit
        {
            get
            {
                if ((this.mUIИмяEdit == null))
                {
                    this.mUIИмяEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIИмяEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Имя";
                    this.mUIИмяEdit.WindowTitles.Add("Открыть");
                    #endregion
                }
                return this.mUIИмяEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIИмяEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITest_oktxtListItem : WinListItem
    {
        
        public UITest_oktxtListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "test_ok.txt";
            this.WindowTitles.Add("Открыть");
            #endregion
        }
        
        #region Properties
        public WinEdit UIИмяEdit
        {
            get
            {
                if ((this.mUIИмяEdit == null))
                {
                    this.mUIИмяEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIИмяEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Имя";
                    this.mUIИмяEdit.WindowTitles.Add("Открыть");
                    #endregion
                }
                return this.mUIИмяEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIИмяEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОткрытьWindow1 : WinWindow
    {
        
        public UIОткрытьWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Открыть");
            #endregion
        }
        
        #region Properties
        public WinSplitButton UIОткрытьSplitButton
        {
            get
            {
                if ((this.mUIОткрытьSplitButton == null))
                {
                    this.mUIОткрытьSplitButton = new WinSplitButton(this);
                    #region Search Criteria
                    this.mUIОткрытьSplitButton.SearchProperties[WinButton.PropertyNames.Name] = "Открыть";
                    this.mUIОткрытьSplitButton.WindowTitles.Add("Открыть");
                    #endregion
                }
                return this.mUIОткрытьSplitButton;
            }
        }
        #endregion
        
        #region Fields
        private WinSplitButton mUIОткрытьSplitButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITerminal1_9_bWindow : WinWindow
    {
        
        public UITerminal1_9_bWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Terminal1_9_b";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Terminal1_9_b");
            #endregion
        }
        
        #region Properties
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow2 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Просмотр элементов";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Terminal1_9_b");
            #endregion
        }
        
        #region Properties
        public UITerminalexeListItem1 UITerminalexeListItem
        {
            get
            {
                if ((this.mUITerminalexeListItem == null))
                {
                    this.mUITerminalexeListItem = new UITerminalexeListItem1(this);
                }
                return this.mUITerminalexeListItem;
            }
        }
        #endregion
        
        #region Fields
        private UITerminalexeListItem1 mUITerminalexeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITerminalexeListItem1 : WinListItem
    {
        
        public UITerminalexeListItem1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Terminal.exe";
            this.WindowTitles.Add("Terminal1_9_b");
            #endregion
        }
        
        #region Properties
        public WinEdit UIИмяEdit
        {
            get
            {
                if ((this.mUIИмяEdit == null))
                {
                    this.mUIИмяEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIИмяEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Имя";
                    this.mUIИмяEdit.WindowTitles.Add("Terminal1_9_b");
                    #endregion
                }
                return this.mUIИмяEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIИмяEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV102Window : WinWindow
    {
        
        public UIТерминалV102Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Terminal v1.9b - 20100630Я - by Br@y++";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMainForm";
            this.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
            #endregion
        }
        
        #region Properties
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow21 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow21(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIТерминалV10TitleBar UIТерминалV10TitleBar
        {
            get
            {
                if ((this.mUIТерминалV10TitleBar == null))
                {
                    this.mUIТерминалV10TitleBar = new UIТерминалV10TitleBar(this);
                }
                return this.mUIТерминалV10TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow3 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIItemWindow21 mUIItemWindow2;
        
        private UIТерминалV10TitleBar mUIТерминалV10TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPanel";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
            #endregion
        }
        
        #region Properties
        public UIТерминалV10Client UIТерминалV10Client
        {
            get
            {
                if ((this.mUIТерминалV10Client == null))
                {
                    this.mUIТерминалV10Client = new UIТерминалV10Client(this);
                }
                return this.mUIТерминалV10Client;
            }
        }
        #endregion
        
        #region Fields
        private UIТерминалV10Client mUIТерминалV10Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV102Client : WinClient
    {
        
        public UIТерминалV102Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
            #endregion
        }
        
        #region Properties
        public WinButton UIConnectButton
        {
            get
            {
                if ((this.mUIConnectButton == null))
                {
                    this.mUIConnectButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIConnectButton.SearchProperties[WinButton.PropertyNames.Name] = "Connect";
                    this.mUIConnectButton.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
                    #endregion
                }
                return this.mUIConnectButton;
            }
        }
        
        public WinButton UIDisconnectButton
        {
            get
            {
                if ((this.mUIDisconnectButton == null))
                {
                    this.mUIDisconnectButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDisconnectButton.SearchProperties[WinButton.PropertyNames.Name] = "Disconnect";
                    this.mUIDisconnectButton.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
                    #endregion
                }
                return this.mUIDisconnectButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIConnectButton;
        
        private WinButton mUIDisconnectButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TEdit";
            this.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow21 : WinWindow
    {
        
        public UIItemWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TGroupBox";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
            #endregion
        }
        
        #region Properties
        public UIТерминалV10Client1 UIТерминалV10Client
        {
            get
            {
                if ((this.mUIТерминалV10Client == null))
                {
                    this.mUIТерминалV10Client = new UIТерминалV10Client1(this);
                }
                return this.mUIТерминалV10Client;
            }
        }
        #endregion
        
        #region Fields
        private UIТерминалV10Client1 mUIТерминалV10Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10Client1 : WinClient
    {
        
        public UIТерминалV10Client1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
            #endregion
        }
        
        #region Properties
        public WinButton UISendButton
        {
            get
            {
                if ((this.mUISendButton == null))
                {
                    this.mUISendButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISendButton.SearchProperties[WinButton.PropertyNames.Name] = "-> Send";
                    this.mUISendButton.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
                    #endregion
                }
                return this.mUISendButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISendButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV102TitleBar : WinTitleBar
    {
        
        public UIТерминалV102TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Terminal v1.9b - 20100630Я - by Br@y++");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10Window1 : WinWindow
    {
        
        public UIТерминалV10Window1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Терминал V1.0";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public UICb_portWindow UICb_portWindow
        {
            get
            {
                if ((this.mUICb_portWindow == null))
                {
                    this.mUICb_portWindow = new UICb_portWindow(this);
                }
                return this.mUICb_portWindow;
            }
        }
        
        public UIОткрытьWindow3 UIОткрытьWindow
        {
            get
            {
                if ((this.mUIОткрытьWindow == null))
                {
                    this.mUIОткрытьWindow = new UIОткрытьWindow3(this);
                }
                return this.mUIОткрытьWindow;
            }
        }
        
        public UITb_send_commandWindow1 UITb_send_commandWindow
        {
            get
            {
                if ((this.mUITb_send_commandWindow == null))
                {
                    this.mUITb_send_commandWindow = new UITb_send_commandWindow1(this);
                }
                return this.mUITb_send_commandWindow;
            }
        }
        
        public UIОтправитьWindow1 UIОтправитьWindow
        {
            get
            {
                if ((this.mUIОтправитьWindow == null))
                {
                    this.mUIОтправитьWindow = new UIОтправитьWindow1(this);
                }
                return this.mUIОтправитьWindow;
            }
        }
        
        public UIТерминалV10TitleBar1 UIТерминалV10TitleBar
        {
            get
            {
                if ((this.mUIТерминалV10TitleBar == null))
                {
                    this.mUIТерминалV10TitleBar = new UIТерминалV10TitleBar1(this);
                }
                return this.mUIТерминалV10TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UICb_portWindow mUICb_portWindow;
        
        private UIОткрытьWindow3 mUIОткрытьWindow;
        
        private UITb_send_commandWindow1 mUITb_send_commandWindow;
        
        private UIОтправитьWindow1 mUIОтправитьWindow;
        
        private UIТерминалV10TitleBar1 mUIТерминалV10TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICb_portWindow : WinWindow
    {
        
        public UICb_portWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cb_port";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICb_portComboBox
        {
            get
            {
                if ((this.mUICb_portComboBox == null))
                {
                    this.mUICb_portComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICb_portComboBox.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUICb_portComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICb_portComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОткрытьWindow3 : WinWindow
    {
        
        public UIОткрытьWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_open_close";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIОткрытьButton
        {
            get
            {
                if ((this.mUIОткрытьButton == null))
                {
                    this.mUIОткрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОткрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Открыть";
                    this.mUIОткрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIОткрытьButton;
            }
        }
        
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОткрытьButton;
        
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITb_send_commandWindow1 : WinWindow
    {
        
        public UITb_send_commandWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "tb_send_command";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinEdit UITb_send_commandEdit
        {
            get
            {
                if ((this.mUITb_send_commandEdit == null))
                {
                    this.mUITb_send_commandEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITb_send_commandEdit.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUITb_send_commandEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITb_send_commandEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОтправитьWindow1 : WinWindow
    {
        
        public UIОтправитьWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_send";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIОтправитьButton
        {
            get
            {
                if ((this.mUIОтправитьButton == null))
                {
                    this.mUIОтправитьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОтправитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Отправить";
                    this.mUIОтправитьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIОтправитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОтправитьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10TitleBar1 : WinTitleBar
    {
        
        public UIТерминалV10TitleBar1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
}
