// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RM_OpenClose - Use 'RM_OpenCloseParams' to pass parameters into this method.
        /// </summary>
        public void RM_OpenClose()
        {
            #region Variable Declarations
            WinButton uIОткрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIОткрытьButton;
            WinButton uIЗакрытьButton = this.UIТерминалV10Window.UIОткрытьWindow.UIЗакрытьButton;
            WinButton uIЗакрытьButton1 = this.UIТерминалV10Window.UIТерминалV10TitleBar.UIЗакрытьButton;
            #endregion

            // Launch 'C:\IU7\Testing\Terminal\CarTerminal_V1.0\Terminal\bin\Debug\Terminal.exe'
            ApplicationUnderTest uIТерминалV10Window = ApplicationUnderTest.Launch(this.RM_OpenCloseParams.UIТерминалV10WindowExePath, this.RM_OpenCloseParams.UIТерминалV10WindowAlternateExePath);

            // Click 'Открыть' button
            Mouse.Click(uIОткрытьButton, new Point(31, 10));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(31, 10));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton1, new Point(24, 13));
        }
        
        #region Properties
        public virtual RM_OpenCloseParams RM_OpenCloseParams
        {
            get
            {
                if ((this.mRM_OpenCloseParams == null))
                {
                    this.mRM_OpenCloseParams = new RM_OpenCloseParams();
                }
                return this.mRM_OpenCloseParams;
            }
        }
        
        public UIТерминалV10Window UIТерминалV10Window
        {
            get
            {
                if ((this.mUIТерминалV10Window == null))
                {
                    this.mUIТерминалV10Window = new UIТерминалV10Window();
                }
                return this.mUIТерминалV10Window;
            }
        }
        #endregion
        
        #region Fields
        private RM_OpenCloseParams mRM_OpenCloseParams;
        
        private UIТерминалV10Window mUIТерминалV10Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RM_OpenClose'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RM_OpenCloseParams
    {
        
        #region Fields
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\CarTerminal_V1.0\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowExePath = "C:\\IU7\\Testing\\Terminal\\CarTerminal_V1.0\\Terminal\\bin\\Debug\\Terminal.exe";
        
        /// <summary>
        /// Launch 'C:\IU7\Testing\Terminal\CarTerminal_V1.0\Terminal\bin\Debug\Terminal.exe'
        /// </summary>
        public string UIТерминалV10WindowAlternateExePath = "C:\\IU7\\Testing\\Terminal\\CarTerminal_V1.0\\Terminal\\bin\\Debug\\Terminal.exe";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10Window : WinWindow
    {
        
        public UIТерминалV10Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Терминал V1.0";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public UIОткрытьWindow UIОткрытьWindow
        {
            get
            {
                if ((this.mUIОткрытьWindow == null))
                {
                    this.mUIОткрытьWindow = new UIОткрытьWindow(this);
                }
                return this.mUIОткрытьWindow;
            }
        }
        
        public UIТерминалV10TitleBar UIТерминалV10TitleBar
        {
            get
            {
                if ((this.mUIТерминалV10TitleBar == null))
                {
                    this.mUIТерминалV10TitleBar = new UIТерминалV10TitleBar(this);
                }
                return this.mUIТерминалV10TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIОткрытьWindow mUIОткрытьWindow;
        
        private UIТерминалV10TitleBar mUIТерминалV10TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIОткрытьWindow : WinWindow
    {
        
        public UIОткрытьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btn_open_close";
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIОткрытьButton
        {
            get
            {
                if ((this.mUIОткрытьButton == null))
                {
                    this.mUIОткрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОткрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Открыть";
                    this.mUIОткрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIОткрытьButton;
            }
        }
        
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОткрытьButton;
        
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIТерминалV10TitleBar : WinTitleBar
    {
        
        public UIТерминалV10TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Терминал V1.0");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Терминал V1.0");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
}
